name: luminarc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  provider: ^6.1.1
  google_fonts: ^6.1.0
  permission_handler: ^11.3.0
  crop_image: ^1.0.12
  screenshot: ^2.1.0
  text_editor: ^0.7.0
  blur: ^3.1.0
  pixel_color_picker: ^1.0.0
  painter: ^2.0.0
  colorfilter_generator: ^0.0.8
  flutter_colorpicker: ^1.0.3
  lindi_sticker_widget: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/stickers/

  fonts:
    # - family: Anonymince Powerline
    #   fonts:
        # - asset: fonts/Anonymince_Powerline_Bold.ttf
        # - asset: fonts/Anonymince_Powerline_Bold_Italic.ttf
        # - asset: fonts/Anonymince_Powerline_Italic.ttf
    - family: Arimo Bold for Powerline
      fonts:
        - asset: fonts/Arimo_Bold_for_Powerline.ttf
    - family: Cousine Bold for Powerline
      fonts:
        - asset: fonts/Cousine_Bold_for_Powerline.ttf
    - family: DejaVu Sans Mono Bold for Powerline
      fonts:
        - asset: fonts/DejaVu_Sans_Mono_Bold_for_Powerline.ttf
    - family: Droid Sans Mono Slashed for Powerline
      fonts:
        - asset: fonts/Droid_Sans_Mono_Slashed_for_Powerline.ttf
